// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GrupoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void grupo() {
    driver.get("https://sso.ufg.br/cas/login?locale=pt_BR&service=https%3A%2F%2Fsigaa.sistemas.ufg.br%2Fsigaa%2FverTelaLogin.do");
    driver.manage().window().setSize(new Dimension(974, 1019));
    driver.findElement(By.id("username")).sendKeys("wendel.filho");
    driver.findElement(By.id("password")).sendKeys("*Wf23571113");
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector(".rc-anchor-checkbox-holder")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.name("submit")).click();
    driver.get("https://sigaa.sistemas.ufg.br/sigaa/portais/discente/discente.jsf");
    driver.findElement(By.id("form_acessarTurmaVirtualj_id_4:turmaVirtual")).click();
    driver.findElement(By.cssSelector(".itemMenuHeaderAlunos:nth-child(1)")).click();
    driver.findElement(By.cssSelector("#formMenu\\3Aj_id_jsp_1448423575_64 a:nth-child(2) > .itemMenu")).click();
    driver.findElement(By.cssSelector(".formAva tr:nth-child(2) > td")).click();
    assertThat(driver.findElement(By.cssSelector(".formAva tr:nth-child(2) > td")).getText(), is("5"));
    driver.get("https://sigaa.sistemas.ufg.br/sigaa/portais/discente/discente.jsf");
    driver.findElement(By.id("form_acessarTurmaVirtualj_id_4:turmaVirtual")).click();
    driver.findElement(By.cssSelector(".itemMenuHeaderAtividades:nth-child(1)")).click();
    driver.findElement(By.cssSelector("#formMenu\\3Aj_id_jsp_1448423575_93 a:nth-child(3) > .itemMenu")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) legend")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) legend")).getText(), is("Tarefas Individuais"));
    driver.findElement(By.cssSelector("tr:nth-child(2) legend")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) legend")).getText(), is("Tarefas Em Grupo"));
    driver.get("https://sigaa.sistemas.ufg.br/sigaa/portais/discente/discente.jsf");
    driver.findElement(By.id("form_acessarTurmaVirtualj_id_4:turmaVirtual")).click();
    driver.findElement(By.cssSelector(".itemMenuHeaderTurma:nth-child(1)")).click();
    driver.findElement(By.cssSelector("#formMenu\\3Aj_id_jsp_1448423575_45 a:nth-child(4) > .itemMenu")).click();
  }
}
