// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GrupoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }

  // Teste de login no SIGAA
  @Test
  public void login() {
    driver.get("https://sso.ufg.br/cas/login?locale=pt_BR&service=https%3A%2F%2Fsigaa.sistemas.ufg.br%2Fsigaa%2FverTelaLogin.do");
    driver.manage().window().setSize(new Dimension(974, 1019));
    driver.findElement(By.id("username")).sendKeys(""); // Username do Discente
    driver.findElement(By.id("password")).sendKeys(""); // Password do Discente
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector(".rc-anchor-checkbox-holder")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.name("submit")).click();
  }

  // Teste para conferir se o número do grupo é 5
  @Test
  public void grupo() {
    driver.get("https://sigaa.sistemas.ufg.br/sigaa/portais/discente/discente.jsf");
    driver.findElement(By.id("form_acessarTurmaVirtualj_id_4:turmaVirtual")).click();
    driver.findElement(By.cssSelector("#formMenu\\3Aj_id_jsp_1448423575_64 a:nth-child(2) > .itemMenu")).click();
    driver.findElement(By.cssSelector(".formAva tr:nth-child(2) > td")).click();
    assertThat(driver.findElement(By.cssSelector(".formAva tr:nth-child(2) > td")).getText(), is("5"));
  }

  // Teste para verificar tarefas individuais e tarefas em grupo
  @Test
  public void tarefa() {
    driver.get("https://sigaa.sistemas.ufg.br/sigaa/portais/discente/discente.jsf");
    driver.findElement(By.id("form_acessarTurmaVirtualj_id_4:turmaVirtual")).click();
    driver.findElement(By.cssSelector("#formMenu\\3Aj_id_jsp_1448423575_93 a:nth-child(3) > .itemMenu")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) legend")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) legend")).getText(), is("Tarefas Individuais"));
    driver.findElement(By.cssSelector("tr:nth-child(2) legend")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) legend")).getText(), is("Tarefas Em Grupo"));
  }

  // Teste para verificar os participantes da matéria
  @Test
  public void participantes() {
    driver.get("https://sigaa.sistemas.ufg.br/sigaa/portais/discente/discente.jsf");
    driver.findElement(By.id("form_acessarTurmaVirtualj_id_4:turmaVirtual")).click();
    driver.findElement(By.cssSelector(".itemMenuHeaderTurma:nth-child(1)")).click();
    driver.findElement(By.cssSelector("#formMenu\\3Aj_id_jsp_1448423575_45 a:nth-child(4) > .itemMenu")).click();
    driver.findElement(By.xpath("//legend[contains(.,\'Alunos (35)\')]")).click();
    assertThat(driver.findElement(By.xpath("//legend[contains(.,\'Alunos (35)\')]")).getText(), is("Alunos (35)"));
  }

  // Teste para verificar notas em outros períodos
  @Test
  public void notas() {
    driver.get("https://sigaa.sistemas.ufg.br/sigaa/portais/discente/discente.jsf");
    driver.findElement(By.cssSelector(".ThemeOfficeMainItemHover > .ThemeOfficeMainFolderText")).click();
    driver.findElement(By.cssSelector("#cmSubMenuID1 .ThemeOfficeMenuItem:nth-child(2) > .ThemeOfficeMenuItemText")).click();
  }

  // Teste para verificar o comprovante de matrícula
  @Test
  public void comprovanteMatricula() {
    driver.get("https://sigaa.sistemas.ufg.br/sigaa/portais/discente/discente.jsf");
    driver.findElement(By.cssSelector(".ThemeOfficeMainItemHover > .ThemeOfficeMainFolderText")).click();
    driver.findElement(By.cssSelector("#cmSubMenuID1 .ThemeOfficeMenuItem:nth-child(3) > .ThemeOfficeMenuItemText")).click();
    driver.findElement(By.cssSelector("h3")).click();
    assertThat(driver.findElement(By.cssSelector("h3")).getText(), is("Comprovante de Matrícula"));

  }
}
